"""
version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/best_model.pkl
      - SCALER_PATH=/app/models/scaler.pkl
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    restart: unless-stopped

  mlflow:
    image: python:3.9-slim
    command: mlflow server --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
      - ./mlartifacts:/mlartifacts
"""